### ISSUE TITLE
Better background color for .well

### ISSUE THREAD

**Issue by coto** [coto/gae-boilerplate#96]
well, this is a twitter-bootstrap issue. and we can overwrite the class to avoid it for now.

I tested last night this boilerplate with an old screen, and color for "well" class (from bootstrap project) couldn't be seen.

Using Chrome dev tools, I change the colors and the best one, similar to the current is:

``` css
.well {
background-image: -webkit-linear-gradient(top, whiteSmoke 0%,#EEE 100%);
background-color: #efefef;
}
```
